#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"

package_site = ARGV.delete("--package")
abort "Usage: ruby scripts/build-anonymous.rb [--package]" unless ARGV.empty?

repo_root = File.expand_path("..", __dir__)
source_path = File.join(repo_root, "index.html")
output_path = File.join(repo_root, "anonymous", "index.html")
html = File.read(source_path)

def replace_once!(html, pattern, replacement, label)
  count = html.scan(pattern).length
  raise "Expected exactly one #{label}; found #{count}." unless count == 1

  html.sub!(pattern, replacement)
end

replace_once!(
  html,
  /(<meta charset="utf-8">)/,
  "\\1\n  <meta name=\"robots\" content=\"noindex, nofollow, noarchive, nosnippet\">",
  "charset meta tag"
)

replace_once!(
  html,
  /            <div class="is-size-5 publication-authors">.*?            <\/div>\n            <div class="is-size-5 publication-authors affiliation-block">.*?            <\/div>/m,
  "            <div class=\"is-size-5 publication-authors\">\n" \
    "              <span class=\"author-block\">Anonymous Authors</span>\n" \
    "            </div>",
  "author and affiliation block"
)

replace_once!(
  html,
  /              <span class="link-block">\n                <a href="https:\/\/github\.com\/[^"]+".*?              <\/span>\n/m,
  "",
  "identifying code link"
)

replace_once!(
  html,
  /  author = \{[^\n]+\},/,
  "  author = {Anonymous Authors},",
  "BibTeX author field"
)

html.gsub!("./static/", "../static/")
html.sub!(
  "<!DOCTYPE html>",
  "<!DOCTYPE html>\n<!-- Generated by scripts/build-anonymous.rb; do not edit directly. -->"
)

forbidden_patterns = [
  /Hanchu/i, /Zhou/i, /Brendan/i, /Lynch/i, /Raman/i, /Goyal/i,
  /Dechen/i, /Gao/i, /Begum/i, /Kasap/i, /Boqi/i, /Zhao/i,
  /Junshan/i, /Zhang/i, /University of California/i, /UC Davis/i,
  /ucd-/i, /Analog Device/i, /github\.com/i
]
leaks = forbidden_patterns.select { |pattern| html.match?(pattern) }
raise "Anonymous page contains identifying text: #{leaks.join(', ')}" unless leaks.empty?

Dir.mkdir(File.dirname(output_path)) unless Dir.exist?(File.dirname(output_path))
File.write(output_path, html)
puts "Generated #{output_path}"

if package_site
  package_path = File.join(repo_root, "dist", "anonymous-site")
  FileUtils.rm_rf(package_path)
  FileUtils.mkdir_p(package_path)
  File.write(File.join(package_path, "index.html"), html.gsub("../static/", "./static/"))
  FileUtils.cp_r(File.join(repo_root, "static"), File.join(package_path, "static"))
  File.write(File.join(package_path, ".nojekyll"), "")
  puts "Packaged deployable site at #{package_path}"
end
